/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("demo.gradle.java-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("demo.gradle.app.App")
}
