/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.demo.app;

import gradle.demo.list.LinkedList;

import static gradle.demo.utilities.StringUtils.join;
import static gradle.demo.utilities.StringUtils.split;
import static gradle.demo.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
