/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.gradle.app;

import demo.gradle.list.LinkedList;

import static demo.gradle.utilities.StringUtils.join;
import static demo.gradle.utilities.StringUtils.split;
import static demo.gradle.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
