/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("gradle.demo.java-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("gradle.demo.app.App")
}
